name: Docker Build & Push

# This Action will:
# - Build a Dockerfile located in the root of the project.
# - Push the new docker image in an ECR Registry.
# - Update a task definition with the new docker image tag.

# ##### GITHUB REQUIRED VARS #####
# AWS_DEFAULT_REGION: Already available in all /gsoftcolombia projects.
# AWS_ROLE_TO_ASSUME: ARN of the role that aws-actions can assume.
# ECR_REPOSITORY: ECR Repository Name
# NAME_PREFIX: Prefix of the task definition in AWS.
# EXECUTION_NAME: Suffix/Postfix of the task definition in AWS. 
#   - If there are multiple task-definitions you can add them separated by ';' e.g. customers;products
#   - If the Action is executed from Main, it expects to update a task definition
#     with the name {NAME_PREFIX}-prod-{EXECUTION_NAME}
#     otherwise, {NAME_PREFIX}-dev-{EXECUTION_NAME}

# ##### USAGE TEMPLATE #####
# on:
#   push:
#     branches:
#     - main
#   pull_request:
#     branches:
#     - main
# 
# jobs:
#   build-push:
#     uses: gsoftcolombia/github-actions/.github/workflows/docker-build-upload.yml@main
#     with:
#       AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
#       AWS_ROLE_TO_ASSUME: ${{ vars.AWS_ROLE_TO_ASSUME }}
#       ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
#       NAME_PREFIX: ${{ vars.NAME_PREFIX }} # Required for both ECS Services and Scheduled Tasks
#
#       DEPLOY_SCHEDULED_TASK: true # Only when you want to deploy scheduled tasks for the app
#       EXECUTION_NAME: ${{ vars.EXECUTION_NAME }} # Only when you want to deploy scheduled tasks
#
#       DEPLOY_ECS_SERVICE: true # Only when you want to deploy a ecs service for the app
#       SERVICE_NAME: ${{ vars.SERVICE_NAME }} # Only when you want to deploy ECS Services
#       ECS_CLUSTER_NAME: ${{ vars.ECS_CLUSTER_NAME }} # Only when you want to deploy ECS Services
#       ECS_DEV_DEPLOY: true # Only when you want to deploy a dev ECS Service for the app



on:
  workflow_call:
    inputs:
      AWS_DEFAULT_REGION: 
        required: true
        type: string
      AWS_ROLE_TO_ASSUME: 
        required: true
        type: string
      ECR_REPOSITORY: 
        required: true
        type: string
      NAME_PREFIX:
        required: true
        type: string
      
      DEPLOY_SCHEDULED_TASK:
        required: true
        type: boolean
      EXECUTION_NAME:
        required: false
        type: string
        default: 'missing_execution_name' # Only when you want to deploy scheduled tasks, it can be a list separated by ';'

      DEPLOY_ECS_SERVICE:
        required: true
        type: boolean
      SERVICE_NAME:
        required: false
        type: string
        default: 'missing_service_name' # Only when you want to deploy a ecs service for the app
      ECS_CLUSTER_NAME:
        required: false # Required if there is SERVICE_NAME
        type: string
        default: 'missing_cluster_name' # Only when you want to deploy a ecs service for the app
      ECS_DEV_DEPLOY:
        required: false
        type: boolean
        default: false

jobs:
  build-push:
    name: Build, Push Docker image and Update Task Definition
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ inputs.AWS_DEFAULT_REGION }}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set short git commit SHA
        id: commit-sha
        run: |
          PR_SHA=${{ github.event.pull_request.head.sha }}
          GITHUB_SHA=${{ github.sha }}
          COMMIT_SHA="${PR_SHA:-$GITHUB_SHA}"
          calculatedSha=$(git rev-parse --short ${COMMIT_SHA})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_OUTPUT
          TASK_ENV=$([ "$GITHUB_REF" = "refs/heads/main" ] && echo "prod" || echo "dev")
          echo "TASK_ENV=$TASK_ENV" >> $GITHUB_OUTPUT
    
      - name: Build and Push to ECR
        continue-on-error: true # for cases when the image is already pushed
        id: build
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.ECR_REPOSITORY }}
        run: |
          IMAGE_ENV=$([ "$GITHUB_REF" = "refs/heads/main" ] && echo "prod" || echo "dev")
          IMAGE_TAG="${IMAGE_ENV}-${{ steps.commit-sha.outputs.COMMIT_SHORT_SHA }}"
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "FULL_IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Deploy ECS Schedule Tasks
        if: ${{ inputs.DEPLOY_SCHEDULED_TASK == true }}
        id: deploy-schedules
        run: |          
          echo "Updating Task Definitions"
          export IFS=";"
          list_execution_name="${{ inputs.EXECUTION_NAME }}"
          for execution_name in $list_execution_name; do
            if ! aws ecs describe-task-definition \
              --task-definition ${{ inputs.NAME_PREFIX }}-${{ steps.commit-sha.outputs.TASK_ENV }}-${execution_name} \
              --region=${{ inputs.AWS_DEFAULT_REGION }} &> /dev/null; then
              echo "ERROR: Task definition ${{ inputs.NAME_PREFIX }}-${{ steps.commit-sha.outputs.TASK_ENV }}-${execution_name} does not exist."
              exit 1
            else
              echo "Updating Task-Definition for: ${execution_name} ..."
              TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition ${{ inputs.NAME_PREFIX }}-${{ steps.commit-sha.outputs.TASK_ENV }}-${execution_name} --region=${{ inputs.AWS_DEFAULT_REGION }})
              updated_task_definition=$(echo $TASK_DEFINITION | jq --slurpfile config .config/${execution_name}.json '.taskDefinition as $base | $config[0] as $updates | reduce ($updates | keys[]) as $key ($base; .[$key] = $updates[$key])')
              NEW_TASK_DEFINITION=$(echo $updated_task_definition | jq --arg IMAGE "${{ steps.build.outputs.FULL_IMAGE_URI }}" '.containerDefinitions[0].image = $IMAGE | del(.taskDefinitionArn) | del(.revision) | del(.status) | del(.requiresAttributes) | del(.compatibilities) | del(.registeredAt) | del(.registeredBy)')
              aws ecs register-task-definition --region ${{ inputs.AWS_DEFAULT_REGION }} --cli-input-json "$NEW_TASK_DEFINITION"
            fi
          done

      - name: Render Amazon ECS Service Task Definition # It only runs when there is an SERVICE_NAME specified.
        if: ${{ inputs.DEPLOY_ECS_SERVICE == true }}
        id: render-web-container
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:          
          task-definition-family: ${{ inputs.NAME_PREFIX }}-${{ steps.commit-sha.outputs.TASK_ENV }}-${{ inputs.SERVICE_NAME }}
          container-name: ${{ inputs.NAME_PREFIX }}-${{ steps.commit-sha.outputs.TASK_ENV }}-${{ inputs.SERVICE_NAME }}
          image: ${{ steps.build.outputs.FULL_IMAGE_URI }}

      - name: Generate appspec.yaml dynamically
        if: ${{ inputs.DEPLOY_ECS_SERVICE == true }}
        id: generate-appspec
        run: |
          cat <<EOF > appspec.yaml
          version: 0.0
          Resources:
            - TargetService:
                Type: AWS::ECS::Service
                Properties:
                  TaskDefinition: "${{ inputs.NAME_PREFIX }}-${{ steps.commit-sha.outputs.TASK_ENV }}-${{ inputs.SERVICE_NAME }}"
                  LoadBalancerInfo:
                    ContainerName: "${{ inputs.NAME_PREFIX }}-${{ steps.commit-sha.outputs.TASK_ENV }}-${{ inputs.SERVICE_NAME }}"
                    ContainerPort: 80
          EOF

      - name: Deploy to Amazon ECS service
        if: ${{ inputs.DEPLOY_ECS_SERVICE == true && (steps.commit-sha.outputs.TASK_ENV == 'prod' || ( steps.commit-sha.outputs.TASK_ENV == 'dev' && inputs.ECS_DEV_DEPLOY == true )) }}
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-web-container.outputs.task-definition }}
          service: ${{ inputs.NAME_PREFIX }}-${{ steps.commit-sha.outputs.TASK_ENV }}-${{ inputs.SERVICE_NAME }}
          cluster: ${{ inputs.ECS_CLUSTER_NAME }}
          wait-for-service-stability: true
          codedeploy-application: ${{ inputs.NAME_PREFIX }}-${{ steps.commit-sha.outputs.TASK_ENV }}-${{ inputs.SERVICE_NAME }}
          codedeploy-deployment-group: ${{ inputs.NAME_PREFIX }}-${{ steps.commit-sha.outputs.TASK_ENV }}-${{ inputs.SERVICE_NAME }}