name: Docker Build & Push

on:
  workflow_call:

env:
 AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}

jobs:
  build-push:
    name: Build, Push Docker image and Update Task Definition
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set short git commit SHA
        id: vars
        run: |
          PR_SHA=${{ github.event.pull_request.head.sha }}
          GITHUB_SHA=${{ github.sha }}
          COMMIT_SHA="${PR_SHA:-$GITHUB_SHA}"
          calculatedSha=$(git rev-parse --short ${COMMIT_SHA})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
    
      - name: Build and Push to ECR
        id: build
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.REPO_NAME }}
        run: |
          IMAGE_ENV=$([ "$GITHUB_REF" = "refs/heads/main" ] && echo "prod" || echo "dev")
          IMAGE_TAG="${IMAGE_ENV}-${COMMIT_SHORT_SHA}"
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "FULL_IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Update ECS Customer Task
        run: |
          TASK_ENV=$([ "$GITHUB_REF" = "refs/heads/main" ] && echo "prod" || echo "dev")
          TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition ${{ vars.APP_NAME_PREFIX }}-$TASK_ENV-${{ vars.APP_NAME_SUFFIX }} --region=${{ vars.AWS_DEFAULT_REGION }})
          NEW_TASK_DEFINTIION=$(echo $TASK_DEFINITION | jq --arg IMAGE "$FULL_IMAGE_URI" '.taskDefinition | .containerDefinitions[0].image = $IMAGE | del(.taskDefinitionArn) | del(.revision) | del(.status) | del(.requiresAttributes) | del(.compatibilities) | del(.registeredAt) | del(.registeredBy)')
          aws ecs register-task-definition --region ${{ vars.AWS_DEFAULT_REGION }} --cli-input-json "$NEW_TASK_DEFINTIION"